### ISSUE TITLE
on ipv6 supporting server stratum sockets are opening only in ipv6 addresses

### ISSUE THREAD

**Issue by konak** [blinkhash/foundation-stratum#20]
Hi !

I have installed foundation-server on my server hosted on provider network and configured both ipv6 and ipv4.
After starting stratum server were opening port only on ipv6 addresses.

locally I have changed code in file of foundation-stratum project:
https://github.com/blinkhash/foundation-stratum/blob/master/scripts/main/network.js
from line 71 to:

      const listenOptions = {
        port: parseInt(currentPort),
        host: "0.0.0.0",
        ipv6Only: false
      };

      // Setup Server to Listen on Port
      server.listen(listenOptions, () => {
        serversStarted += 1;
        if (serversStarted == stratumPorts.length) {
          _this.emit('started');
        }
      });

Server started listening to on ipv4 address ..
If it is Ok, I can make that change in the project.

Wish you all the best !

**Comment by blinkhash** [comment]
Seems like a good change, thanks for the contribution! I'll review it further if you open a PR

**Comment by konak** [comment]
Will check the case to accept connections on IPv6 and IPv4 concurrently and will make a PR in this two days.

**Comment by konak** [comment]
Need some doublechecking on the server where I had that issue. Seems that issue does not exist on lates version of node. It is starting listen on IPv6 port like:


    root@xx:/home/ttt# netstat -na | grep 2299
    tcp6       0      0 :::2299                 :::*                    LISTEN


but accepting connections from IPv4 too:


    root@xx:/home/ttt# netstat -na | grep 2299
    tcp6       0      0 :::2299                 :::*                    LISTEN
    tcp6       0      0 65.108.84.205:2299      37.157.212.30:55355     ESTABLISHED

It will be possible to do in next two days, when I will put the server to maintenance mode.
Sorry for inconvenience.

**Comment by konak** [comment]
I have doublechecked the code on the server had that issue. Everything were working just fine without any code changes. Seems the issue was in node version or in some other thing. So there is no any need to make changes in the code. With current implementation server is starting listen on IPv6 port but it is also accepting IPv4 connections.
Sorry for inconvenience. My fault.
